### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by x0n4d0** [x0n4d0/minbackup-script#1]
### INÍCIO DO PROJETO
- [ ] Criar diretório de documentação
- [ ] CHANGELOG.md
- [ ] NEWS.md
- [ ] MINBACKUP.md

### FUNÇÕES
- [ ] Criar módulo principal
- [ ] Criar método para backup dos arquivos importantes no celular
